"repository":
  "name": "event-dispatcher"
  "description": "Event Dispatcher implementation."
  "homepage": "https://github.com/ghostwriter/event-dispatcher"
  "topics": "event-dispatcher, ghostwriter"
  "has_issues": true
  "has_projects": false
  "has_wiki": false
  "has_downloads": true
  "default_branch": "5.0.x"
  "allow_squash_merge": true
  "allow_merge_commit": true
  "allow_rebase_merge": true
  "delete_branch_on_merge": true
  "enable_automated_security_fixes": true
  "enable_vulnerability_alerts": true
  "allow_auto_merge": true
  "allow_update_branch": true
  "web_commit_signoff_required": true
"milestones":
  - "title": "5.1.0"
    "description": "Minor release – targeting 5.1.x branch (semantic version: 5.1.0)"
    "state": "open"
  - "title": "5.0.4"
    "description": "Patch release – targeting 5.0.x branch (semantic version: 5.0.4)"
    "state": "open"
  - "title": "5.1.1"
    "description": "Patch release – targeting 5.1.x branch (semantic version: 5.1.1)"
    "state": "open"
  - "title": "6.0.0"
    "description": "Major release – targeting 6.0.x branch (semantic version: 6.0.0)"
    "state": "open"
  - "title": "5.0.3"
    "description": "Patch release – targeting 5.0.x branch (semantic version: 5.0.3)"
    "state": "closed"
